[theme]
base = "dark"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
port = 8501

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[runner]
magicEnabled = false

[global]
developmentMode = false
