# Streamlit Cloud Secrets Configuration
# This file is automatically managed by Streamlit Cloud
# Do not commit sensitive information here

# OpenAI Configuration
OPENAI_API_KEY = "your_openai_api_key_here"

# Application Settings
DEFAULT_LANGUAGE = "EN"
MAX_CONVERSATION_LENGTH = "50"
DEFAULT_EXPORT_FORMAT = "docx"
EXPORT_FOLDER = "exports"
